name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.16
      with:
        cuda: "12.4.0"  # Specifying the CUDA version to match your local setup
        sub-packages: '["nvcc", "curand-dev"]'  # Including necessary sub-packages
        method: network  # Using network method for installation
        use-github-cache: true  # Enabling GitHub cache for faster builds
        use-local-cache: true  # Enabling local cache for faster installations
        log-file-suffix: log.txt  # Setting a suffix for log files

    - name: Compile the CUDA program
      run: |
        cd src
        nvcc -o game game.cu

    - name: Run CUDA program
      run: ./src/game
