name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.16
      with:
        cuda: "12.6.0"
        sub-packages: '["nvcc"]'
        method: network
        use-github-cache: true
        use-local-cache: true
        log-file-suffix: log.txt

    - name: Compile the CUDA program
      run: |
        cd src
        nvcc -o game game.cu

    - name: Run CUDA program
      run: ./src/game
